apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-hibrido
  namespace: default
  labels:
    app: app-teste
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-teste
  template:
    metadata:
      labels:
        app: app-teste
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        # Removi as seções env, volumeMounts e volumes
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: servico-clusterip
spec:
  type: ClusterIP
  selector:
    app: app-teste  # Aponta para o Deployment acima
  ports:
    - port: 80        # Porta que o serviço expõe
      targetPort: 80  # Porta do Nginx