apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-hibrido
  namespace: default
  labels:
    app: app-teste
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-teste
  template:
    metadata:
      labels:
        app: app-teste
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: servico-nodeport
spec:
  type: NodePort      # MUDANÇA: Tipo alterado para NodePort
  selector:
    app: app-teste
  ports:
    - port: 80        # Porta interna do Serviço (ClusterIP)
      targetPort: 80  # Porta do Container
      nodePort: 30007 # MUDANÇA: Porta fixa exposta para fora (30000-32767)