apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ssd-required
  namespace: lab
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-ssd-required
  template:
    metadata:
      labels:
        app: nginx-ssd-required
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disco
                operator: In
                values:
                - ssd
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
