apiVersion: v1
kind: Pod
metadata:
  name: pod-capacidade-alta
  namespace: lab
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: capacidade
            operator: Gt
            values:
            - "60"
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
