apiVersion: v1
kind: Pod
metadata:
  name: pod-completao
  namespace: default
  labels:
    app: site-teste
spec:
  # 1. DEFINIÇÃO DO VOLUME 
  # (A "caixa" de armazenamento)
  volumes:
  - name: meu-volume-temporario
    emptyDir: {} # Cria uma pasta vazia temporária no Node

  containers:
  - name: nginx
    image: nginx:alpine
    
    # 2. PORTA 
    # (Onde o processo escuta)
    ports:
    - containerPort: 80
      name: http
      protocol: TCP

    # 3. MONTAGEM DO VOLUME 
    # (Onde a "caixa" é conectada dentro do container)
    volumeMounts:
    - name: meu-volume-temporario
      mountPath: /usr/share/nginx/html

    resources:
      requests:
        cpu: "0.1"
        memory: "64Mi"
      limits:
        cpu: "0.5"
        memory: "128Mi"