apiVersion: v1
kind: Pod
metadata:
  name: pod-burstable
  namespace: lab
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "500m"
