apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-com-cache
  namespace: lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-com-cache
  template:
    metadata:
      labels:
        app: webapp-com-cache
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - cache
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
