apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-spread
  namespace: lab
spec:
  replicas: 6
  selector:
    matchLabels:
      app: webapp-spread
  template:
    metadata:
      labels:
        app: webapp-spread
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - webapp-spread
              topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
